server:
  port: 8300

spring:
  application:
    name: gateway-service

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka


# Map paths to services
zuul:
  routes:
    auth-service:
      path: /auth/**
      service-id: auth-service
    config-service:
      path: /config/**
      service-id: config-service