server:
  port: 8100

spring:
  application:
    name: config-service

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka


auth-service:
  ribbon:
    eureka:
      enabled: false
    listOfServers: localhost:8200,localhost:9092,localhost:9999
    ServerListRefreshInterval: 15000